services:
  db:
    image: postgres:16
    container_name: nowarie-db
    environment:
      POSTGRES_USER: nowarie
      POSTGRES_PASSWORD: nowarie
      POSTGRES_DB: nowarie
    ports:
      - "5432:5432"
    volumes:
      - nowarie-data:/var/lib/postgresql/data

volumes:
  nowarie-data: